# Generated by Django 4.2.16 on 2024-10-28 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])], verbose_name='Изображение дизайна'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'unique': 'Категория с таким названием уже существует'}, max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='image',
            field=models.ImageField(upload_to='design_requests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено')], default='Новая', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
